// import { app, BrowserWindow } from 'electron';
// // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// // plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// // whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// import { createFileRoute, createURLRoute } from 'electron-router-dom'

// // Handle creating/removing shortcuts on Windows when installing/uninstalling.
// if (require('electron-squirrel-startup')) {
//   app.quit();
// }

// const createWindow = (): void => {
//   // Create the browser window.
//   const mainWindow = new BrowserWindow({
//     height: 600,
//     width: 800,
//     webPreferences: {
//       preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
//     },
//   });

//   // and load the index.html of the app.
//   // mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
//   const devServerURL = createURLRoute(MAIN_WINDOW_WEBPACK_ENTRY, 'main')
//   mainWindow.loadURL(devServerURL);

//   // Open the DevTools.
//   mainWindow.webContents.openDevTools();
// };

// // This method will be called when Electron has finished
// // initialization and is ready to create browser windows.
// // Some APIs can only be used after this event occurs.

// app.on('ready', createWindow);

// // Quit when all windows are closed, except on macOS. There, it's common
// // for applications and their menu bar to stay active until the user quits
// // explicitly with Cmd + Q.
// app.on('window-all-closed', () => {
//   if (process.platform !== 'darwin') {
//     app.quit();
//   }
// });

// app.on('activate', () => {
//   // On OS X it's common to re-create a window in the app when the
//   // dock icon is clicked and there are no other windows open.
//   if (BrowserWindow.getAllWindows().length === 0) {
//     createWindow();
//   }
// });

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

import {
  app,
  BrowserWindow,
  BrowserWindowConstructorOptions as WindowOptions,
} from 'electron'

import { createFileRoute, createURLRoute } from 'electron-router-dom'
import { join } from 'path'

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

function createWindow(id: string, options: WindowOptions = {}) {
  const window = new BrowserWindow({
    width: 700,
    height: 473,
    autoHideMenuBar: true,
    webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
          },
    ...options,
  })

  const fileRoute = createFileRoute(
    join(__dirname, '../renderer/main_window/index.html'),
    id
  )
  // window.loadFile(...fileRoute)
  const devServerURL = createURLRoute(MAIN_WINDOW_WEBPACK_ENTRY, id)
  console.log(process.env.APP_NAME);
  console.log("=======");
  
  
  if(process.env.NODE_ENV === 'development'){
    window.loadURL(devServerURL)
    window.webContents.openDevTools();
    console.log(process.env.NODE_ENV);
    console.log("dev");
    
  }else{
    console.log("prod");
    window.loadFile(...fileRoute)
  }
  return window
}
app.whenReady().then(() => {
  createWindow('main', {
    title:"Testing Main"
    // webPreferences: {
    //   preload: join(__dirname, '../renderer/main_window/preload.js'),
    // },
  })
  createWindow('about', {
    show: false,
    title:"About"
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
